"""modify NotificationType enums

Revision ID: 48ef455a6386
Revises: 0eec1a73db4e
Create Date: 2025-08-22 07:18:44.745697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48ef455a6386'
down_revision: Union[str, Sequence[str], None] = '0eec1a73db4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE notificationtype ADD VALUE IF NOT EXISTS 'SYSTEM_ALERT';")

    print("✅ Added missing notification type enum values")
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    print("⚠️ Downgrade: Enum values left in place (PostgreSQL limitation)")
    print("   Manual cleanup required if you need to remove these values")
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
