"""add assignment_declined status to swap requests

Revision ID: 4cc4d61b34b8
Revises: 1f1906d93afd
Create Date: 2025-07-13 04:27:55.975238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cc4d61b34b8'
down_revision: Union[str, Sequence[str], None] = '1f1906d93afd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
