"""add schedule constraints

Revision ID: 6aebbf9184c2
Revises: 13ee0498c64f
Create Date: 2025-07-06 06:16:00.164387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6aebbf9184c2'
down_revision: Union[str, Sequence[str], None] = '13ee0498c64f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduleconfig',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('min_rest_hours', sa.Integer(), nullable=False),
    sa.Column('max_consecutive_days', sa.Integer(), nullable=False),
    sa.Column('max_weekly_hours', sa.Integer(), nullable=False),
    sa.Column('min_staff_per_shift', sa.Integer(), nullable=False),
    sa.Column('max_staff_per_shift', sa.Integer(), nullable=False),
    sa.Column('require_manager_per_shift', sa.Boolean(), nullable=False),
    sa.Column('shift_role_requirements', sa.JSON(), nullable=True),
    sa.Column('allow_overtime', sa.Boolean(), nullable=False),
    sa.Column('weekend_restrictions', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('shift_assignment')
    op.drop_table('staff_unavailability')
    op.alter_column('schedule', 'facility_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('schedule', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('staff', 'skill_level',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff', 'skill_level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('schedule', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('schedule', 'facility_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_table('staff_unavailability',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('staff_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('staff_unavailability_staff_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('staff_unavailability_pkey'))
    )
    op.create_table('shift_assignment',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('schedule_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('day', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shift', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('staff_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], name=op.f('shift_assignment_schedule_id_fkey')),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('shift_assignment_staff_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('shift_assignment_pkey'))
    )
    op.drop_table('scheduleconfig')
    # ### end Alembic commands ###
