"""add updated_at to schedule

Revision ID: 7750191f6fad
Revises: 9ef2df2f6261
Create Date: 2025-07-09 09:49:24.032553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7750191f6fad'
down_revision: Union[str, Sequence[str], None] = '9ef2df2f6261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'updated_at')
    # ### end Alembic commands ###
