"""Add is_published field

Revision ID: 7ab32cde80ed
Revises: a4d163b17d4a
Create Date: 2025-08-14 00:26:48.017555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ab32cde80ed'
down_revision: Union[str, Sequence[str], None] = 'a4d163b17d4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('is_published', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('schedule', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('schedule', sa.Column('published_by_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(
        "fk_schedule_published_by_id_user",  # name
        "schedule",
        "user",
        ["published_by_id"],
        ["id"]
    )
    op.alter_column('schedule', 'is_published', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_schedule_published_by_id_user", "schedule", type_="foreignkey")
    op.drop_column('schedule', 'published_by_id')
    op.drop_column('schedule', 'published_at')
    op.drop_column('schedule', 'is_published')
    # ### end Alembic commands ###
