"""Add account linking

Revision ID: 899f22794e11
Revises: e45b65b3f802
Create Date: 2025-08-20 12:47:48.738935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '899f22794e11'
down_revision: Union[str, Sequence[str], None] = 'e45b65b3f802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userprovider',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('provider_email', sa.String(), nullable=False),
    sa.Column('provider_data', sa.JSON(), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userprovider_provider'), 'userprovider', ['provider'], unique=False)
    op.create_index(op.f('ix_userprovider_provider_email'), 'userprovider', ['provider_email'], unique=False)
    op.create_index(op.f('ix_userprovider_provider_id'), 'userprovider', ['provider_id'], unique=False)
    op.create_index(op.f('ix_userprovider_user_id'), 'userprovider', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userprovider_user_id'), table_name='userprovider')
    op.drop_index(op.f('ix_userprovider_provider_id'), table_name='userprovider')
    op.drop_index(op.f('ix_userprovider_provider_email'), table_name='userprovider')
    op.drop_index(op.f('ix_userprovider_provider'), table_name='userprovider')
    op.drop_table('userprovider')
    # ### end Alembic commands ###
