"""add emergency swap tables

Revision ID: 8af26142e5d6
Revises: bbee5dd00bab
Create Date: 2025-07-06 07:39:49.453588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8af26142e5d6'
down_revision: Union[str, Sequence[str], None] = 'bbee5dd00bab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swaprequest',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('schedule_id', sa.Uuid(), nullable=False),
    sa.Column('requesting_staff_id', sa.Uuid(), nullable=False),
    sa.Column('original_day', sa.Integer(), nullable=False),
    sa.Column('original_shift', sa.Integer(), nullable=False),
    sa.Column('swap_type', sa.String(), nullable=False),  # Changed
    sa.Column('target_staff_id', sa.Uuid(), nullable=True),
    sa.Column('target_day', sa.Integer(), nullable=True),
    sa.Column('target_shift', sa.Integer(), nullable=True),
    sa.Column('assigned_staff_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),  # Changed
    sa.Column('urgency', sa.String(), nullable=False),  # Changed
    sa.Column('status', sa.String(), nullable=False),   # Changed
    sa.Column('target_staff_accepted', sa.Boolean(), nullable=True),
    sa.Column('manager_approved', sa.Boolean(), nullable=True),
    sa.Column('manager_notes', sa.String(), nullable=True),  # Changed
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['requesting_staff_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.ForeignKeyConstraint(['target_staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('swaphistory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('swap_request_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),  # Changed
    sa.Column('actor_staff_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),    # Changed
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_staff_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['swap_request_id'], ['swaprequest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swaphistory')
    op.drop_table('swaprequest')
    # ### end Alembic commands ###
