"""include swap assignment

Revision ID: 973351c59e6a
Revises: c46eb53f6d44
Create Date: 2025-07-24 15:50:08.544289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '973351c59e6a'
down_revision: Union[str, Sequence[str], None] = 'c46eb53f6d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE notificationtype ADD VALUE 'SWAP_ASSIGNMENT'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
