"""Add is_active field

Revision ID: a4d163b17d4a
Revises: 4c57554cac6f
Create Date: 2025-08-08 08:20:20.159653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4d163b17d4a'
down_revision: Union[str, Sequence[str], None] = '4c57554cac6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facility', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facility', 'is_active')
    # ### end Alembic commands ###
