"""Add account verification token

Revision ID: a895b7b3c96c
Revises: 899f22794e11
Create Date: 2025-08-20 14:44:06.739504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a895b7b3c96c'
down_revision: Union[str, Sequence[str], None] = '899f22794e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accountverificationtoken',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('provider_email', sa.String(), nullable=False),
    sa.Column('provider_data', sa.JSON(), nullable=True),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accountverificationtoken_code_hash'), 'accountverificationtoken', ['code_hash'], unique=False)
    op.create_index(op.f('ix_accountverificationtoken_email'), 'accountverificationtoken', ['email'], unique=False)
    op.create_index(op.f('ix_accountverificationtoken_user_id'), 'accountverificationtoken', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accountverificationtoken_user_id'), table_name='accountverificationtoken')
    op.drop_index(op.f('ix_accountverificationtoken_email'), table_name='accountverificationtoken')
    op.drop_index(op.f('ix_accountverificationtoken_code_hash'), table_name='accountverificationtoken')
    op.drop_table('accountverificationtoken')
    # ### end Alembic commands ###
