"""add is_super_admin

Revision ID: ba0cd9d33bba
Revises: ca3d79f3f972
Create Date: 2025-08-21 06:30:52.701125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba0cd9d33bba'
down_revision: Union[str, Sequence[str], None] = 'ca3d79f3f972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   # Add with a temporary server default so existing rows get FALSE
    op.add_column(
        'user',
        sa.Column('is_super_admin', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    # Remove the default so future inserts must set it explicitly (or use app default)
    op.alter_column('user', 'is_super_admin', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_super_admin')
    # ### end Alembic commands ###
