"""add reason and recurring to staff unavailability

Revision ID: bbee5dd00bab
Revises: 6aebbf9184c2
Create Date: 2025-07-06 07:00:50.699480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbee5dd00bab'
down_revision: Union[str, Sequence[str], None] = '6aebbf9184c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###
