"""add actor_user_id to swaphistory

Revision ID: c46eb53f6d44
Revises: 2b61d3d85e76
Create Date: 2025-07-24 07:23:45.652480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c46eb53f6d44'
down_revision: Union[str, Sequence[str], None] = '2b61d3d85e76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('swaphistory', sa.Column('actor_user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'swaphistory', 'user', ['actor_user_id'], ['id'])
    op.alter_column('swaprequest', 'status',
               existing_type=postgresql.ENUM('pending', 'manager_approved', 'potential_assignment', 'staff_accepted', 'manager_final_approval', 'executed', 'staff_declined', 'assignment_declined', 'assignment_failed', 'declined', 'cancelled', name='swapstatus'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('swaprequest', 'status',
               existing_type=postgresql.ENUM('pending', 'manager_approved', 'potential_assignment', 'staff_accepted', 'manager_final_approval', 'executed', 'staff_declined', 'assignment_declined', 'assignment_failed', 'declined', 'cancelled', name='swapstatus'),
               nullable=False)
    op.drop_constraint(None, 'swaphistory', type_='foreignkey')
    op.drop_column('swaphistory', 'actor_user_id')
    # ### end Alembic commands ###
