"""add enum types

Revision ID: ca3d79f3f972
Revises: a895b7b3c96c
Create Date: 2025-08-20 21:18:51.861967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca3d79f3f972'
down_revision: Union[str, Sequence[str], None] = 'a895b7b3c96c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE notificationtype ADD VALUE IF NOT EXISTS 'SWAP_ASSIGNMENT';")
    op.execute("ALTER TYPE notificationtype ADD VALUE IF NOT EXISTS 'PASSWORD_RESET';")
    op.execute("ALTER TYPE notificationtype ADD VALUE IF NOT EXISTS 'EMAIL_VERIFICATION';")
    op.execute("ALTER TYPE notificationtype ADD VALUE IF NOT EXISTS 'STAFF_INVITATION';")
    op.execute("ALTER TYPE notificationtype ADD VALUE IF NOT EXISTS 'ACCOUNT_LINKED';")
    
    print("✅ Added missing notification type enum values")
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    print("⚠️ Downgrade: Enum values left in place (PostgreSQL limitation)")
    print("   Manual cleanup required if you need to remove these values")
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
