"""add email to staff

Revision ID: e5963a09ba3f
Revises: 8af26142e5d6
Create Date: 2025-07-07 13:57:04.205046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5963a09ba3f'
down_revision: Union[str, Sequence[str], None] = '8af26142e5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('staff', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('staff', 'email')
    # ### end Alembic commands ###
