"""add WELCOME_EMAIL enum

Revision ID: efb809c0a040
Revises: ba0cd9d33bba
Create Date: 2025-08-21 07:01:49.658005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efb809c0a040'
down_revision: Union[str, Sequence[str], None] = 'ba0cd9d33bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE notificationtype ADD VALUE IF NOT EXISTS 'WELCOME_EMAIL';")
    print("✅ Added WELCOME_EMAIL notification type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    print("⚠️ Downgrade: WELCOME_EMAIL enum value left in place (PostgreSQL limitation)")
    # ### end Alembic commands ###
