// Auto-generated en translations
// Generated by Auto-Translator script

export const en = {
  common: {
    sEmailAddressNameStringUser: 's email address
  name: string         // User',
  },

} as const;

export default en;