// Auto-generated Italian translations
// Generated by Auto-Translator script

export const it = {
  common: {
    sEmailAddressNameStringUser: 's email address
  name: string         // User',
  },

} as const;

export default it;